spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bebeshop
    username: postgres
    password: dkskTlqkf
    driver-class-name: org.postgresql.Driver

  jpa:
    show_sql: true
    database: postgresql
    default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace